CREATE DATABASE italbolt
	CHARACTER SET utf8
	COLLATE utf8_hungarian_ci;

CREATE TABLE italbolt.category (
  id INT(11) NOT NULL AUTO_INCREMENT,
  CategoryName VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 15,
AVG_ROW_LENGTH = 1170,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

CREATE TABLE italbolt.item (
  id INT(11) NOT NULL AUTO_INCREMENT,
  categoryesId INT(11) DEFAULT NULL,
  itemName VARCHAR(255) DEFAULT NULL,
  Image VARCHAR(255) DEFAULT NULL,
  unit VARCHAR(255) DEFAULT NULL,
  alcoholcontent INT(11) DEFAULT NULL,
  brand VARCHAR(255) DEFAULT NULL,
  weighting INT(11) DEFAULT NULL,
  ratingId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

ALTER TABLE italbolt.item 
  ADD CONSTRAINT FK_items_kategoria_id FOREIGN KEY (categoryesId)
    REFERENCES italbolt.category(id);

CREATE TABLE italbolt.itemprice (
  id INT(11) NOT NULL AUTO_INCREMENT,
  itemId INT(11) DEFAULT NULL,
  Date DATETIME DEFAULT NULL,
  price INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 9,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

ALTER TABLE italbolt.itemprice 
  ADD CONSTRAINT FK_itemprice_item_id FOREIGN KEY (itemId)
    REFERENCES italbolt.item(id);

CREATE TABLE italbolt.user (
  id INT(11) NOT NULL AUTO_INCREMENT,
  firstName VARCHAR(255) DEFAULT NULL,
  lastName VARCHAR(255) DEFAULT NULL,
  gender VARCHAR(255) DEFAULT NULL,
  email VARCHAR(50) DEFAULT NULL,
  password VARCHAR(255) DEFAULT NULL,
  phoneNumber VARCHAR(255) DEFAULT NULL,
  permission INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 2,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

CREATE TABLE italbolt.userrating (
  id INT(11) NOT NULL AUTO_INCREMENT,
  userId INT(11) DEFAULT NULL,
  comment VARCHAR(255) DEFAULT NULL,
  rating INT(11) DEFAULT NULL,
  itemId INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8,
COLLATE utf8_hungarian_ci;

ALTER TABLE italbolt.userrating 
  ADD CONSTRAINT FK_userrating_item_id FOREIGN KEY (itemId)
    REFERENCES italbolt.item(id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE italbolt.userrating 
  ADD CONSTRAINT FK_userrating_user_id FOREIGN KEY (userId)
    REFERENCES italbolt.user(id);